name: Run Golangci-Lint

on:
  pull_request:
    branches:
      - main
      - prod
      - staging

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.61

          # arguments
          args: --exclude-dirs-use-default=true

          # Optional: working directory, useful for monorepo
          working-directory: ./

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
