name: Build and Deploy Staging Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_ACCESS_KEY_SECRET}}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{steps.login-ecr.outputs.registry}}
          REPOSITORY: lokatalent/backend
          IMAGE_TAG: staging-latest
        run: |
          pip3 install awscli
          aws s3 cp s3://lokatalent-storage/env/.env.staging ./.env
          docker buildx build --tag $REGISTRY/$REPOSITORY:$IMAGE_TAG --file Dockerfile.aws .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
